// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TournoiArchipelago.Api.Data;

#nullable disable

namespace TournoiArchipelago.Api.Migrations
{
    [DbContext(typeof(TournoiDbContext))]
    [Migration("20260907205232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Joueur1Id")
                        .HasColumnType("int")
                        .HasColumnName("joueur1_id");

                    b.Property<int>("Joueur2Id")
                        .HasColumnType("int")
                        .HasColumnName("joueur2_id");

                    b.HasKey("Id")
                        .HasName("PK_Equipe");

                    b.HasIndex("Joueur1Id");

                    b.HasIndex("Joueur2Id");

                    b.ToTable("Equipe", (string)null);
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Jeu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("PK_Jeu");

                    b.ToTable("Jeu", (string)null);
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("PK_joueur");

                    b.ToTable("Joueur", (string)null);
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK_Match");

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.MatchJeu", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("match_id");

                    b.Property<int>("JeuId")
                        .HasColumnType("int")
                        .HasColumnName("jeu_id");

                    b.Property<int>("JoueurId")
                        .HasColumnType("int")
                        .HasColumnName("joueur_id");

                    b.Property<string>("Seed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seed");

                    b.Property<TimeSpan?>("TempsFinalSecs")
                        .HasColumnType("time")
                        .HasColumnName("temps_final_secs");

                    b.Property<int?>("TotalChecks")
                        .HasColumnType("int")
                        .HasColumnName("total_checks");

                    b.HasKey("MatchId", "JeuId", "JoueurId")
                        .HasName("PK_MatchJeu");

                    b.HasIndex("JeuId");

                    b.HasIndex("JoueurId");

                    b.ToTable("MatchJeu", (string)null);
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Equipe", b =>
                {
                    b.HasOne("TournoiArchipelago.Api.Domain.Joueur", "Joueur1")
                        .WithMany()
                        .HasForeignKey("Joueur1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Equipe_Joueur1");

                    b.HasOne("TournoiArchipelago.Api.Domain.Joueur", "Joueur2")
                        .WithMany()
                        .HasForeignKey("Joueur2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Equipe_Joueur2");

                    b.Navigation("Joueur1");

                    b.Navigation("Joueur2");
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.MatchJeu", b =>
                {
                    b.HasOne("TournoiArchipelago.Api.Domain.Jeu", "Jeu")
                        .WithMany("MatchJeux")
                        .HasForeignKey("JeuId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_MatchJeu_Jeu");

                    b.HasOne("TournoiArchipelago.Api.Domain.Joueur", "Joueur")
                        .WithMany("MatchJeux")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_MatchJeu_Joueur");

                    b.HasOne("TournoiArchipelago.Api.Domain.Match", "Match")
                        .WithMany("MatchJeux")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_MatchJeu_Match");

                    b.Navigation("Jeu");

                    b.Navigation("Joueur");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Jeu", b =>
                {
                    b.Navigation("MatchJeux");
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Joueur", b =>
                {
                    b.Navigation("MatchJeux");
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Match", b =>
                {
                    b.Navigation("MatchJeux");
                });
#pragma warning restore 612, 618
        }
    }
}
