// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TournoiArchipelago.Api.Data;

#nullable disable

namespace TournoiArchipelago.Api.Migrations
{
    [DbContext(typeof(TournoiDbContext))]
    partial class TournoiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Joueur1Id")
                        .HasColumnType("int")
                        .HasColumnName("joueur1_id");

                    b.Property<int>("Joueur2Id")
                        .HasColumnType("int")
                        .HasColumnName("joueur2_id");

                    b.HasKey("Id")
                        .HasName("PK_Equipe");

                    b.HasIndex("Joueur2Id");

                    b.HasIndex("Joueur1Id", "Joueur2Id")
                        .IsUnique()
                        .HasDatabaseName("UQ_Equipe_joueurs");

                    b.ToTable("Equipe", null, t =>
                        {
                            t.HasCheckConstraint("CK_Equipe_membres_distincts", "[joueur1_id] <> [joueur2_id]");
                        });
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Jeu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("PK_Jeu");

                    b.HasIndex("Nom")
                        .IsUnique()
                        .HasDatabaseName("UQ_Jeu_nom");

                    b.ToTable("Jeu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "A Link to the Past"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Ocarina of Time"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Super Metroid"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Super Mario World"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Hollow Knight"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Timespinner"
                        },
                        new
                        {
                            Id = 7,
                            Nom = "Risk of Rain 2"
                        },
                        new
                        {
                            Id = 8,
                            Nom = "Factorio"
                        },
                        new
                        {
                            Id = 9,
                            Nom = "Stardew Valley"
                        },
                        new
                        {
                            Id = 10,
                            Nom = "Donkey Kong Country 3"
                        },
                        new
                        {
                            Id = 11,
                            Nom = "Pokemon Red and Blue"
                        },
                        new
                        {
                            Id = 12,
                            Nom = "Castlevania 64"
                        });
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("PK_joueur");

                    b.HasIndex("Nom")
                        .IsUnique()
                        .HasDatabaseName("UQ_Joueur_nom");

                    b.ToTable("Joueur", (string)null);
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK_Match");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Match_date");

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.MatchJeu", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("match_id");

                    b.Property<int>("JeuId")
                        .HasColumnType("int")
                        .HasColumnName("jeu_id");

                    b.Property<int>("JoueurId")
                        .HasColumnType("int")
                        .HasColumnName("joueur_id");

                    b.Property<int?>("NbChecks")
                        .HasColumnType("int")
                        .HasColumnName("nb_checks");

                    b.Property<string>("Seed")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("seed");

                    b.Property<int?>("TempsFinalSecs")
                        .HasColumnType("int")
                        .HasColumnName("temps_final_secs");

                    b.Property<int?>("TotalChecks")
                        .HasColumnType("int")
                        .HasColumnName("total_checks");

                    b.HasKey("MatchId", "JeuId", "JoueurId")
                        .HasName("PK_MatchJeu");

                    b.HasIndex("JeuId");

                    b.HasIndex("JoueurId");

                    b.HasIndex("MatchId", "JoueurId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MatchJeu_match_joueur");

                    b.ToTable("MatchJeu", (string)null);
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Equipe", b =>
                {
                    b.HasOne("TournoiArchipelago.Api.Domain.Joueur", "Joueur1")
                        .WithMany()
                        .HasForeignKey("Joueur1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Equipe_Joueur1");

                    b.HasOne("TournoiArchipelago.Api.Domain.Joueur", "Joueur2")
                        .WithMany()
                        .HasForeignKey("Joueur2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Equipe_Joueur2");

                    b.Navigation("Joueur1");

                    b.Navigation("Joueur2");
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.MatchJeu", b =>
                {
                    b.HasOne("TournoiArchipelago.Api.Domain.Jeu", "Jeu")
                        .WithMany("MatchJeux")
                        .HasForeignKey("JeuId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_MatchJeu_Jeu");

                    b.HasOne("TournoiArchipelago.Api.Domain.Joueur", "Joueur")
                        .WithMany("MatchJeux")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_MatchJeu_Joueur");

                    b.HasOne("TournoiArchipelago.Api.Domain.Match", "Match")
                        .WithMany("MatchJeux")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MatchJeu_Match");

                    b.Navigation("Jeu");

                    b.Navigation("Joueur");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Jeu", b =>
                {
                    b.Navigation("MatchJeux");
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Joueur", b =>
                {
                    b.Navigation("MatchJeux");
                });

            modelBuilder.Entity("TournoiArchipelago.Api.Domain.Match", b =>
                {
                    b.Navigation("MatchJeux");
                });
#pragma warning restore 612, 618
        }
    }
}
